services:
  ruby:
    from: ruby:2.3.1
    cache:
      - /bundle
    build:
      - apt-get update
      - gem install bundler
      - apt-get install -y nodejs mysql-client postgresql-client sqlite3
      - apt-get install -y curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev libxml2-dev libxslt-dev

test:
  prepare:
    - bundle install --path /bundle
  service: ruby
  folder: /app
  cmd: bin/rspec -f d
  env:
    - RACK_ENV=test
